# MEMAHAMI DATA

### PENGERTIAN BUNGA IRIS

Bunga iris adalah tanaman yang memiliki keindahan warna dan bentuk yang menarik. Tanaman ini dapat diperjualbelikan secara bebas dan sering digunakan sebagai tanaman hias. Anda dapat menanamnya dalam pot atau langsung di tanah halaman rumah.

Selain sebagai tanaman hias, bunga iris juga memiliki manfaat sebagai tanaman obaT. Beberapa kondisi yang dapat diobati dengan bunga iris meliputi:

1. Hepatitis: Bunga iris dapat membantu mengatasi masalah hati seperti hepatitis.
2. Mual: Ekstrak bunga iris dapat membantu meredakan rasa mual.
3. Sembelit: Bunga iris memiliki sifat pencahar ringan yang dapat membantu mengatasi sembelit.
4. Rematik: Beberapa orang menggunakan bunga iris untuk mengurangi gejala rematik.
5. Gusi Bengkak: Bunga iris juga dapat membantu mengurangi peradangan pada gusi.

### Pada pertemuan kali ini akan memahami hal hal berikut

- mendeskripsikan fitur

- Amati missing value

- Inputasi missing value dengan metode KNN dan Mean lalu dibandingkan

- Hitung akurasi dan perbandingan tiap metode

<img src="hqdefault.jpg" width="" align="" />

### tools dan melakukan inisialiasasi

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

## MEMANGGIL DATA DARI SQL

In [2]:
df_sepal = _deepnote_execute_sql('SELECT * FROM iris;', 'SQL_9F3F03B5_F8B8_4A07_80A1_96272AD8CCBC', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_sepal

NameError: name '_deepnote_execute_sql' is not defined

## MEMANGGIL DATA DARI POSTGRESQL

In [3]:
df_petal = _deepnote_execute_sql('SELECT * FROM iris;\n', 'SQL_6F84781F_577D_4D8A_83A4_FC7E0CA2EC1D', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_petal

id  petallengthcm  petalwidthcm         species
0      1            1.4           0.2     Iris-setosa
1      2            1.4           0.2     Iris-setosa
2      3            1.3           0.2     Iris-setosa
3      4            1.5           0.2     Iris-setosa
4      5            1.4           0.2     Iris-setosa
..   ...            ...           ...             ...
145  146            5.2           2.3  Iris-virginica
146  147            5.0           1.9  Iris-virginica
147  148            5.2           2.0  Iris-virginica
148  149            5.4           2.3  Iris-virginica
149  150            5.1           1.8  Iris-virginica

[150 rows x 4 columns]

## MENGGABUNGKAN 2 DATA DARI DATABASE BERBEDA 

MENJADI 1 DATA 

In [4]:
df = pd.concat([df_sepal.drop(['Species'], axis=1), df_petal.drop(['id'], axis=1)], axis=1, join='inner')

df

Id  SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

## DESKRIPSI TENTANG DATA 

### FITUR

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   petallengthcm  150 non-null    float64
 4   petalwidthcm   150 non-null    float64
 5   species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


### penjelasan

1.RangeIndex (Indeks Rentang): 

 Indeks ini menunjukkan jumlah baris dalam DataFrame. Pada kasus ini, terdapat 150 entri, mulai dari indeks 0 hingga 149.

2.Data Columns (Kolom Data):

1.Id: Kolom ini berisi nilai-nilai integer yang mewakili identifikasi unik untuk setiap entri.
2.SepalLengthCm: Kolom ini berisi nilai panjang sepal (bagian daun) dalam satuan sentimeter.
3.SepalWidthCm: Kolom ini berisi nilai lebar sepal dalam satuan sentimeter.
4.petallengthcm: Kolom ini berisi nilai panjang kelopak bunga dalam satuan sentimeter.
5.petalwidthcm: Kolom ini berisi nilai lebar kelopak bunga dalam satuan sentimeter.
6.species: Kolom ini berisi informasi tentang spesies bunga (misalnya, “setosa”, “versicolor”, atau “virginica”)

DataFrame ini tampaknya berisi data tentang bunga iris. Data ini dapat digunakan untuk analisis atau pemodelan lebih lanjut. Jika Anda memiliki pertanyaan lebih lanjut tentang DataFrame ini, jangan ragu untuk bertanya!

In [6]:
df.value_counts('species')

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

Dari kode program diatas. dapat diketahui bahwa terdapat tiga jenis bunga iris berdasarkan data yang sudah kita analisa.

## Percobaan melakukan mising value

Pada tahap ini, kita akan melakukan percobaan dengan menghapus lima nilai dari beberapa baris data. Dengan demikian, kita secara tidak langsung mensimulasikan situasi di mana data memiliki nilai yang hilang atau missing value.

Dalam analisis data, menghadapi nilai yang hilang adalah tantangan yang umum. Simulasi ini memungkinkan kita untuk memahami bagaimana model atau metode yang kita gunakan akan berperilaku ketika menghadapi data yang tidak lengkap. Dengan memahami cara mengelola nilai yang hilang, kita dapat mengambil keputusan yang lebih baik dalam pemodelan dan analisis data

## Menghapus value dari baris

In [7]:
df.loc[df["Id"] == 50, 'SepalLengthCm'] = None
df.loc[df["Id"] == 100, 'SepalLengthCm'] = None
df.loc[df["Id"] == 150, 'SepalLengthCm'] = None

# dua fitur pada 
df.loc[df["Id"] == 25, ['SepalLengthCm','PetalWidthCm']] = None
df.loc[df["Id"] == 75, ['SepalLengthCm','PetalWidthCm']] = None

df

Id  SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            NaN           3.0            5.1           1.8   

            species  PetalWidthCm  
0       Iris-setosa           NaN  
1       Iris-setosa           NaN  
2       Iris-setosa           NaN  
3       Iris-setosa           NaN  
4       Iris-setosa           NaN  
..              ...           ...  
145  Iris-virginica           NaN  
146  Iris-virginica           NaN  
147  Iris-virginica           NaN  
148  Iris-virginica           NaN  
149  Iris-virginica           NaN  

[150 rows x 7 columns]

## Menampilkan fitur yang memiliki missing value

In [8]:
df.isnull().sum()

Id                 0
SepalLengthCm      5
SepalWidthCm       0
petallengthcm      0
petalwidthcm       0
species            0
PetalWidthCm     150
dtype: int64

Dari kode di atas, kita dapat melihat bahwa terdapat nilai yang hilang (missing value) pada dua fitur:

1. SepalLengthCm: Terdapat lima baris yang memiliki nilai yang hilang pada fitur ini.
2. PetalWidthCm: Terdapat dua baris yang memiliki nilai yang hilang pada fitur ini.

Dalam analisis data, mengelola nilai yang hilang adalah langkah penting untuk memastikan hasil yang akurat dan konsisten

Data preprocessing dalam data mining memainkan peran yang sangat penting. Pada tahapan ini, data mentah (raw data) diolah sehingga dapat diubah menjadi data yang dapat dianalisis lebih lanjut.

## Pra-pemrosesan Data (Data Preprocessing)

Berikut adalah empat tahap pra-pemrosesan data:

1. Pembersihan Data (Data Cleaning):
    - Pada tahap ini, data mentah yang diperoleh harus diseleksi dengan menghapus data yang tidak relevan, tidak lengkap, atau tidak akurat. Tujuannya adalah untuk mengurangi kesalahan interpretasi data.

2. Penggabungan Data (Data Integration):
    - Data dari berbagai sumber yang berbeda digabungkan menjadi satu dataset. Penting untuk memastikan bahwa sumber data memiliki format yang seragam.

3. Transformasi Data (Data Transformation):
    - Setelah proses penggabungan data dari berbagai sumber, langkah selanjutnya adalah melakukan transformasi data. Ini diperlukan karena kemungkinan data yang diambil memiliki perbedaan format. Dengan menyamakan format data, proses analisis lebih mudah dilakukan.

4. Pengurangan Data (Data Reduction):
    - Tahap terakhir adalah mengurangi jumlah data. Meskipun kita mengurangi sampel data, hal ini tidak boleh mengubah hasil analisis. Ada tiga cara yang umum digunakan:
        - Mengurangi Dimensi: Mengurangi jumlah fitur atau variabel yang digunakan.
        - Pengurangan Jumlah Data: Mengambil sampel data yang lebih kecil.
        - Kompresi Data: Mengurangi ukuran data tanpa menghilangkan informasi penting.

Semua tahapan ini membantu memastikan bahwa data yang digunakan untuk analisis lebih lanjut adalah data yang berkualitas 

## 1. Pembersihan Data (Data Cleaning)

### A.Seleksi fitur

In [9]:
df = df.drop(['Id'], axis=1)

df

SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm         species  \
0              5.1           3.5            1.4           0.2     Iris-setosa   
1              4.9           3.0            1.4           0.2     Iris-setosa   
2              4.7           3.2            1.3           0.2     Iris-setosa   
3              4.6           3.1            1.5           0.2     Iris-setosa   
4              5.0           3.6            1.4           0.2     Iris-setosa   
..             ...           ...            ...           ...             ...   
145            6.7           3.0            5.2           2.3  Iris-virginica   
146            6.3           2.5            5.0           1.9  Iris-virginica   
147            6.5           3.0            5.2           2.0  Iris-virginica   
148            6.2           3.4            5.4           2.3  Iris-virginica   
149            NaN           3.0            5.1           1.8  Iris-virginica   

     PetalWidthCm  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
..            ...  
145           NaN  
146           NaN  
147           NaN  
148           NaN  
149           NaN  

[150 rows x 6 columns]

seleksi fitur dilakukan untuk menghapus kolom atau fitur yang tidak relevan atau tidak diperlukan dalam analisis atau komputasi lebih lanjut. Dalam kasus ini, kolom “Id” dihapus karena memang tidak dibutuhkan dalam proses pemodelan atau perhitungan.

Dengan menghilangkan fitur yang tidak relevan, kita dapat meningkatkan efisiensi dan akurasi model

### B.Merubah nama kolom

In [10]:
df = df.rename(columns={'SepalLengthCm' : 'Sepal Length', 'SepalWidthCm' : 'Sepal Width', 'PetalLengthCm' : 'Petal Length', 'PetalWidthCm' : 'Petal Width'})

df.head(5)

Sepal Length  Sepal Width  petallengthcm  petalwidthcm      species  \
0           5.1          3.5            1.4           0.2  Iris-setosa   
1           4.9          3.0            1.4           0.2  Iris-setosa   
2           4.7          3.2            1.3           0.2  Iris-setosa   
3           4.6          3.1            1.5           0.2  Iris-setosa   
4           5.0          3.6            1.4           0.2  Iris-setosa   

   Petal Width  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

Berikut adalah beberapa langkah yang dapat diambil untuk mengubah nama kolom

Renaming Kolom:
Anda dapat menggunakan metode atau fungsi yang disediakan oleh pustaka analisis data (seperti Pandas di Python) untuk mengganti nama kolom. Misalnya, dalam Pandas, Anda dapat menggunakan metode .rename() untuk mengganti nama kolom.


Menggunakan Nama yang Lebih Deskriptif:
Berikan nama yang lebih jelas dan deskriptif untuk setiap kolom. Misalnya, jika kita memiliki kolom dengan nama “X1”, kita dapat menggantinya dengan “Usia” atau “Pendapatan”.


Hindari Spasi dan Karakter Khusus:
Gunakan format yang konsisten dan hindari spasi atau karakter khusus dalam nama kolom. Jika perlu, gantilah spasi dengan garis bawah atau huruf kapital.


Singkat dan Jelas:
Pastikan nama kolom singkat dan mudah dipahami. Hindari penggunaan kata-kata yang terlalu panjang atau ambigu.

### C.Menghapus baris duplikat

In [11]:
# cek jumlah baris dan kolom
df.shape

(150, 6)

In [12]:
# cek jumlah baris dan kolom yang memiliki data duplikat
duplicate_rows_df = df[df.duplicated()]

print('number of duplicate rows : ', duplicate_rows_df.shape)

number of duplicate rows :  (3, 6)


Dari kode program diatas, dapat diketahui bahwa terdapat tiga baris yang memilki data yang sama

In [13]:
# menghapus duplikasi data
df = df.drop_duplicates()

print('number of rows after drop duplicated rows', df.shape)

number of rows after drop duplicated rows (147, 6)


Berdasarkan output kode proram diatas, jumlah baris yang awalnya 150 baris menjadi 147 baris. hal ini membuktikan bahwa kita sudah berhasil menghapus baris yang memiliki data yang sama.

## Penanganan missing value

Pentingnya menangani data yang hilang atau kosong tidak boleh diabaikan. Ketidakhadiran data ini dapat mengganggu proses pemodelan dataset, menghasilkan hasil yang tidak akurat atau tidak dapat diandalkan. Sumber data yang tidak berfungsi dengan baik, entah itu dari mesin atau manusia, dapat menjadi penyebab kehilangan data. Kesalahan dalam proses pengolahan atau kesalahan manusia dalam pengumpulan data juga dapat menjadi penyebabnya.

Ada beberapa pendekatan yang dapat dilakukan dalam penanganan nilai yang hilang. Salah satunya adalah dengan menghapus data yang hilang, tetapi juga dapat diisi kembali menggunakan berbagai metode. Dua metode umum yang akan dicoba dalam kasus ini adalah pengisian dengan nilai rata-rata (mean) dan menggunakan metode K Nearest Neighbor (KNN).

In [14]:
print(df.columns)

Index(['Sepal Length', 'Sepal Width', 'petallengthcm', 'petalwidthcm',
       'species', 'Petal Width'],
      dtype='object')


In [15]:
# menampilkan baris dengan missing value
df.loc[df['Sepal Length'].isnull() | df['Sepal Width'].isnull() | df['petallengthcm'].isnull() | df['petalwidthcm'].isnull()]

Sepal Length  Sepal Width  petallengthcm  petalwidthcm          species  \
24            NaN          3.4            1.9           0.2      Iris-setosa   
49            NaN          3.3            1.4           0.2      Iris-setosa   
74            NaN          2.9            4.3           1.3  Iris-versicolor   
99            NaN          2.8            4.1           1.3  Iris-versicolor   
149           NaN          3.0            5.1           1.8   Iris-virginica   

     Petal Width  
24           NaN  
49           NaN  
74           NaN  
99           NaN  
149          NaN

In [16]:
# menghapus baris baris dengan missing value pada kolom 'Petal Width'
df.dropna(subset=['petalwidthcm'], inplace=True)

In [17]:
df

Sepal Length  Sepal Width  petallengthcm  petalwidthcm         species  \
0             5.1          3.5            1.4           0.2     Iris-setosa   
1             4.9          3.0            1.4           0.2     Iris-setosa   
2             4.7          3.2            1.3           0.2     Iris-setosa   
3             4.6          3.1            1.5           0.2     Iris-setosa   
4             5.0          3.6            1.4           0.2     Iris-setosa   
..            ...          ...            ...           ...             ...   
145           6.7          3.0            5.2           2.3  Iris-virginica   
146           6.3          2.5            5.0           1.9  Iris-virginica   
147           6.5          3.0            5.2           2.0  Iris-virginica   
148           6.2          3.4            5.4           2.3  Iris-virginica   
149           NaN          3.0            5.1           1.8  Iris-virginica   

     Petal Width  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
..           ...  
145          NaN  
146          NaN  
147          NaN  
148          NaN  
149          NaN  

[147 rows x 6 columns]

## Penanganan missing value dengan metode nilai rata-rata (Mean)

Pada tahap sebelumnya, kita berhasil menghapus baris yang mengandung nilai yang hilang. Pada langkah ini, kita akan mengisi nilai yang hilang dengan menggunakan metode rata-rata (Mean). Metode ini melibatkan penjumlahan semua nilai fitur dalam kolom dan kemudian melakukan pembagian dengan jumlah baris. Ini akan menghasilkan rata-rata nilai fitur. Berikut adalah rumusnya:

Dengan menggunakan rumus ini, kita dapat menemukan nilai rata-rata untuk setiap fitur dalam dataset. Selanjutnya, nilai rata-rata ini akan digunakan untuk mengisi nilai yang hilang dalam dataset.

In [18]:
# membuat copy dataframe pada variabel lain
df_mean = df.copy(deep=True)

# mencari nilai mean
mean = round(df_mean['Sepal Length'].mean(), 1)

print('nilai mean adalah = ', mean)

# imputasi missing value dengan mean
df_mean['Sepal Length'].fillna(mean, inplace=True)

df_mean

nilai mean adalah =  5.9


Sepal Length  Sepal Width  petallengthcm  petalwidthcm         species  \
0             5.1          3.5            1.4           0.2     Iris-setosa   
1             4.9          3.0            1.4           0.2     Iris-setosa   
2             4.7          3.2            1.3           0.2     Iris-setosa   
3             4.6          3.1            1.5           0.2     Iris-setosa   
4             5.0          3.6            1.4           0.2     Iris-setosa   
..            ...          ...            ...           ...             ...   
145           6.7          3.0            5.2           2.3  Iris-virginica   
146           6.3          2.5            5.0           1.9  Iris-virginica   
147           6.5          3.0            5.2           2.0  Iris-virginica   
148           6.2          3.4            5.4           2.3  Iris-virginica   
149           5.9          3.0            5.1           1.8  Iris-virginica   

     Petal Width  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
..           ...  
145          NaN  
146          NaN  
147          NaN  
148          NaN  
149          NaN  

[147 rows x 6 columns]

Berdasarkan kode program diatas. kita membuat duplikasi dataframe yang nantinya untuk menyipan dataframe yang menggunakan metode mean. kemudian mencari nilai mean dan timpa atau gantikan baris yang memiliki missing value dengan nilai mean.

## Penanganan missing value dengan metode K Nearest Neightbour (KNN)

Jika kita merujuk pada ide "K Nearest Neightbour" atau "Tetangga Terdekat K", itu adalah sebuah metode di mana kita mencari sejumlah tetangga terdekat dari data yang ingin diprediksi, dan kemudian membandingkan kelas dari tetangga tersebut untuk memprediksi kelas dari data yang baru. Jadi, kita dapat menggambarkan KNN sebagai teknik yang menggunakan jumlah tetangga terdekat untuk memprediksi kelasifikasi data baru. Penjelasan lebih rinci tentang cara kerjanya dapat ditemukan di bawah ini.

<img src="image-20240314-093855.png" width="" align="" />

1.INITIAL DATA

Algoritma KNN melakukan klasifikasi dengan memproyeksikan data pembelajaran ke dalam ruang berdimensi banyak.
Ruang ini dibagi menjadi bagian-bagian yang merepresentasikan kriteria data .
Setiap data pembelajaran direpresentasikan sebagai titik-titik dalam ruang berdimensi banyak.
Proses klasifikasi dilakukan dengan mencari titik terdekat dari data baru menggunakan formula jarak, seperti jarak Euclidean, jarak Hamming, Manhattan Distance, atau Minkowski Distance.
Teknik pencarian tetangga terdekat disesuaikan dengan dimensi data, proyeksi, dan kemudahan implementasi oleh pengguna.

2.CALCULATE DISTANCE

<img src="image-20240314-095109.png" width="" align="" />

$d(P,Q) = \sqrt{\sum_{i=1}^{n} (p_{i} - q_{i})^2}$

$d(P,Q) = \sqrt{(p_{1} - q_{1})^2 + (p_{2} - q_{2})^2 + ... + (p_{n} - q_{n})^2}$

<img src="image-20240314-095609.png" width="" align="" />

In [19]:
from sklearn.impute import KNNImputer

# duplikasi dataframe
df_knn = df.copy(deep=True)

# simpan class species
df_species = df_knn[['species']]

list_species = df_species.values.tolist()

#hapus kolom yang tidak diperlukan
df_knn = df_knn.drop(['species'], axis=1)

# old_value = df_knn.drop(['species'], axis=1).to_numpy()

# inisialisasi KNNImputer
imputer = KNNImputer(n_neighbors=3)

# simpan kalkulasi
result = imputer.fit_transform(df_knn)

result = result.tolist()

# gabung hasil dengan class
for index in range(len(result)):
    result[index].append(list_species[index][0])

# buat dataframe
df_knn = pd.DataFrame(result, columns=['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width', 'Species'])

df_knn

Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0        5.100000          3.5           1.4          0.2     Iris-setosa
1        4.900000          3.0           1.4          0.2     Iris-setosa
2        4.700000          3.2           1.3          0.2     Iris-setosa
3        4.600000          3.1           1.5          0.2     Iris-setosa
4        5.000000          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
142      6.700000          3.0           5.2          2.3  Iris-virginica
143      6.300000          2.5           5.0          1.9  Iris-virginica
144      6.500000          3.0           5.2          2.0  Iris-virginica
145      6.200000          3.4           5.4          2.3  Iris-virginica
146      6.433333          3.0           5.1          1.8  Iris-virginica

[147 rows x 5 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8912165a-7e42-4d21-9551-d1060fd57f14' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>